main: de.pixelstudios.mcreloaded.MCReloaded
name: MCReloaded
version: Alpha0.4.1
author: AidenRocktDas
api-version: 1.16
website: www.pixel-deluxe.net

commands:
  menu:
  profile:
  gm:
  friend:
  ping:
  fly:
  repair:
  profile:
  mcreloaded:
  mcr:
  cords:
  cordinates:
  reload:
  rl:
  gamemode:
  stop: